/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721Simple__factory } from "./ERC721Simple__factory";
export { MockToken__factory } from "./MockToken__factory";
